#!/bin/bash
#SBATCH -J tomo  # Job name
#SBATCH -p gpuserv # Queue name (another queue - compclass)
#SBATCH -e launch.err # Name of stderr file (%j expands to %jobId)
#SBATCH -o launch.out  # Name of stdout output file (%j expands to %jobId)
#SBATCH -N 1   # Total number of nodes requested
#SBATCH -c 4   # CPUs per task
#SBATCH -t 20:00:00 # Maximal run time (hh:mm:ss) - 1 minute
. $CONDA_ROOT/etc/profile.d/conda.sh

module load nvidia/cuda
echo "Current path=`pwd`"
echo "node=`hostname`"
echo "nproc=`nproc`"
nvcc --version
echo $SLURM_JOBID
echo $SLURM_SUBMIT_DIR
echo $SLURM_JOB_NODELIST
echo $SLURM_CPUS_PER_TASK
echo $SLURM_NTASKS
nvidia-smi
conda activate env_realsr
cd /home/d_korostelev/Projects/super_resolution/Real-ESRGAN
CUDA_VISIBLE_DEVICES="1" python inference_realesrgan.py -n RealESRGAN_x4plus -i datasets/real/rgb_cropped/glass/lr_images -o predictions/glass/lr_images_latest --model_path experiments/finetune_paired_glass/models/net_g_latest.pth
