#!/bin/bash
#SBATCH --job-name=jupyter
#SBATCH --partition=gpuserv
#SBATCH --time=2-00:00:00
#SBATCH --output=./jupyter.log

. $CONDA_ROOT/etc/profile.d/conda.sh
conda activate env_realsr

cat /etc/hosts
jupyter lab --ip=0.0.0.0 --port=8888
