#!/bin/bash
#SBATCH --job-name=jupyter
#SBATCH --partition=gpuserv
#SBATCH -e launch.err # Name of stderr file (%j expands to %jobId)
#SBATCH -o launch.out  # Name of stdout output file (%j expands to %jobId)
#SBATCH --time=2-00:00:00
#SBATCH --output=./jupyter.log

. $CONDA_ROOT/etc/profile.d/conda.sh
conda activate env_realsr

cat /etc/hosts
jupyter lab --port=8881
